# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Email - Tests

on:
  # [push]
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Send email
        
        if: success()
        # You may pin to the exact commit or the version.
        # uses: dawidd6/action-send-mail@v2
        uses: dawidd6/action-send-mail@v3.7.1
        
        with:
          server_address: smtp.gmail.com
          convert_markdown: true
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # Subject of mail message
          
          subject: Test
          # Recipients mail addresses (separated with comma)
          to: ${{ secrets.CC_EMAIL_RECIPIENT }}
          
          # Full name of mail sender (might be with an email address specified in <>)
          from: The Big D
          # Body of mail message (might be a filename prefixed with file:// to read from)
          # body: 
          # HTML body of mail message (might be a filename prefixed with file:// to read from)
          # Files that will be added to mail message attachments (separated with comma)
          #attachments: # optional
          #attachments: ./dist/static/*.js

